version: "2"

services:
  redis:
    image: "alpine/socat"
    container_name: socat
    restart: "always"
    volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
    - "2375:2375"
    command: "tcp-listen:2375,fork,reuseaddr unix-connect:/var/run/docker.sock"

networks:
  default:
    external:
      name: my_network
